### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by YorickPeterse** [YorickPeterse/ruby-ll#14]
While ruby-ll should for the most part support Windows just fine there are a few things left to take care of:

* Compiler flags, as discussed originally in https://github.com/YorickPeterse/ruby-ll/pull/13
* Automated testing, there was some CI for this but I keep forgetting the name

**Comment by djberg96** [comment]
http://www.appveyor.com/

**Comment by YorickPeterse** [comment]
Yeah, found it after googling a bit. Setting it up at the moment to see how that goes.

**Comment by YorickPeterse** [comment]
Hmpf, seems I can't find a way to get Ragel installed on AppVeyor as its required during development (and I don't want to track the generated files in Git). On top of that I don't know if Ragel works on Windows in the first place.

**Comment by YorickPeterse** [comment]
@djberg96 What do the following expressions return on Windows?:

* `RbConfig::CONFIG['host_os']`
* `RbConfig::CONFIG['arch']`

**Comment by djberg96** [comment]
I installed the precompiled binary for it and it seemed to work fine.

**Comment by djberg96** [comment]
irb(main):001:0> RbConfig::CONFIG['host_os']
    => "mswin32_120"
    irb(main):002:0> RbConfig::CONFIG['arch']
    => "i386-mswin32_120"

**Comment by YorickPeterse** [comment]
> I installed the precompiled binary for it and it seemed to work fine.

The only one I can find (http://w858rkbfg.homepage.t-online.de/index.php/software/ragel-windows/) is for Ragel 6.8. I'm not sure how future proof it's going to be to download some random binary not made by the maintainer of Ragel, especially with Ragel 7 coming soon (tm). 

Also, what does `RUBY_PLATFORM` return on Windows?

**Comment by djberg96** [comment]
Yeah, that's what I used, but the tests all passed (except one that was just a case of assuming /tmp instead of C:/tmp somewhere).

    irb(main):001:0> RUBY_PLATFORM
    => "i386-mswin32_120"

**Comment by YorickPeterse** [comment]
How exactly did you go about installing it in that case? Do you just dump it somewhere and update whatever the equivalent is of `$PATH` on Windows?

**Comment by djberg96** [comment]
Yup, stuck it in C:/usr/ragel and added C:/usr/ragel/bin to %PATH%.

**Comment by YorickPeterse** [comment]
Ah, seems AppVeyor can partially take care of this http://www.appveyor.com/docs/how-to/download-file. Also another question, what's the VisualStudio equivalent of `-O3`?

**Comment by djberg96** [comment]
I'll let you decide. I think Ruby does /O2sy by default. 

    /O1 minimize space                      /O2 maximize speed
    /Ob<n> inline expansion (default n=0)   /Od disable optimizations (default)
    /Og enable global optimization          /Oi[-] enable intrinsic functions
    /Os favor code space                    /Ot favor code speed
    /Ox maximum optimizations               /Oy[-] enable frame pointer omission

**Comment by djberg96** [comment]
CFLAGS => -MD -Zi -W2 -wd4996 -we4028 -we4142 -O2sy-  -Zm600

**Comment by YorickPeterse** [comment]
Fixed in the master branch, released as 2.1.1. AppVeyor is still a bit buggy (e.g. builds sometimes stall at random points) but for the most part it's working.
