### ISSUE TITLE
ELL(1) Support

### ISSUE THREAD

**Issue by pabloh** [YorickPeterse/ruby-ll#5]
Have you consider adding support for Extended LL(1) grammars?.

**Comment by YorickPeterse** [comment]
I've never heard of ELL(1), are there any resources on this?

**Comment by pabloh** [comment]
Yeap, for some reason most of them are only on books/papers: https://books.google.com.ar/books?id=05xA_d5dSwAC&lpg=PA259&ots=3OsveDl7Mb&dq=%22ell(1)%22%20grammars&pg=PA259#v=onepage&q=%22ell(1)%22%20grammars&f=false .

It's simply the extension of what you allowed at the right hand side of productions using some elements from regular expressions. You basically add the * (star), + (plus) and ? (optional) metasyntactic constructs to the grammar definition language. They are essentially a case of Extended Context Free Grammars (ECFG).

**Comment by YorickPeterse** [comment]
Ah, actually ruby-ll had support for these operators early on but they were removed in d09972fc6ec300fd7ee2bbba8e8d39294aa42707. These operators were basically syntax sugar and so the following (for example)

    rule = number*;

Would get turned into:

    rule = rule1;
    rule1 = rule2 | _;
    rule2 = number | rule1;

I'm thinking of re-introducing them at some point, but I'm not sure when and in what fashion.

**Comment by pabloh** [comment]
I see. It would be cool to have them back since they can make some syntaxes' definition a lot more succinct.

**Comment by YorickPeterse** [comment]
Correct, not having them can lead to quite verbose LL(1) grammars. I'll give this some thought to see if I can come up with a nice way of re-introducing these operators.

**Comment by pabloh** [comment]
Great!

**Comment by YorickPeterse** [comment]
Since I'll need this for Oga (due to recursion being right-associative) I'll be implementing this in the coming week or so. Progress can be tracked on the branch [operators](https://github.com/YorickPeterse/ruby-ll/tree/operators) branch

**Comment by pabloh** [comment]
Cool

**Comment by YorickPeterse** [comment]
@pabloh PR #12 contains the required bits and pieces to support the `*` and `+` operators (I dropped `?` since it's not really useful). Some example docs on these operators:

* https://github.com/YorickPeterse/ruby-ll/tree/operators#operators
* https://github.com/YorickPeterse/ruby-ll/blob/operators/examples/math.rll

If there's anything I might've missed, feel free to tell me. I'll be testing the new operators a bit more and probably merge/release it in the coming days.
